package com.ebs.mapper;

import com.ebs.model.Abc;

public interface AbcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated
     */
    int insert(Abc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abc
     *
     * @mbggenerated
     */
    int insertSelective(Abc record);
}