package com.ebs.mapper;

import com.ebs.model.QuaninfoBean;

public interface QuaninfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_quaninfo
     *
     * @mbggenerated
     */
    int insert(QuaninfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_quaninfo
     *
     * @mbggenerated
     */
    int insertSelective(QuaninfoBean record);
}