package com.ebs.mapper;

import com.ebs.model.RoleBean;

public interface RoleBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rolecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbggenerated
     */
    int insert(RoleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbggenerated
     */
    int insertSelective(RoleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbggenerated
     */
    RoleBean selectByPrimaryKey(String rolecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleBean record);
}