package com.ebs.model;

public class Abc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abc.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abc.age
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abc.username
     *
     * @return the value of abc.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abc.username
     *
     * @param username the value for abc.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abc.age
     *
     * @return the value of abc.age
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abc.age
     *
     * @param age the value for abc.age
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }
}