package com.ebs.model;

import java.util.Date;

public class QuaninfoBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.SRLNO
     *
     * @mbggenerated
     */
    private Long srlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.PARAMSRLNO
     *
     * @mbggenerated
     */
    private Long paramsrlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.QNAME
     *
     * @mbggenerated
     */
    private String qname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.QURL
     *
     * @mbggenerated
     */
    private String qurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.MID
     *
     * @mbggenerated
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.PID
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.EFFDATE
     *
     * @mbggenerated
     */
    private Date effdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.INVALDATE
     *
     * @mbggenerated
     */
    private Date invaldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_quaninfo.PARAMSTATE
     *
     * @mbggenerated
     */
    private String paramstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.SRLNO
     *
     * @return the value of p_quaninfo.SRLNO
     *
     * @mbggenerated
     */
    public Long getSrlno() {
        return srlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.SRLNO
     *
     * @param srlno the value for p_quaninfo.SRLNO
     *
     * @mbggenerated
     */
    public void setSrlno(Long srlno) {
        this.srlno = srlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.PARAMSRLNO
     *
     * @return the value of p_quaninfo.PARAMSRLNO
     *
     * @mbggenerated
     */
    public Long getParamsrlno() {
        return paramsrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.PARAMSRLNO
     *
     * @param paramsrlno the value for p_quaninfo.PARAMSRLNO
     *
     * @mbggenerated
     */
    public void setParamsrlno(Long paramsrlno) {
        this.paramsrlno = paramsrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.QNAME
     *
     * @return the value of p_quaninfo.QNAME
     *
     * @mbggenerated
     */
    public String getQname() {
        return qname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.QNAME
     *
     * @param qname the value for p_quaninfo.QNAME
     *
     * @mbggenerated
     */
    public void setQname(String qname) {
        this.qname = qname == null ? null : qname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.QURL
     *
     * @return the value of p_quaninfo.QURL
     *
     * @mbggenerated
     */
    public String getQurl() {
        return qurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.QURL
     *
     * @param qurl the value for p_quaninfo.QURL
     *
     * @mbggenerated
     */
    public void setQurl(String qurl) {
        this.qurl = qurl == null ? null : qurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.MID
     *
     * @return the value of p_quaninfo.MID
     *
     * @mbggenerated
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.MID
     *
     * @param mid the value for p_quaninfo.MID
     *
     * @mbggenerated
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.PID
     *
     * @return the value of p_quaninfo.PID
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.PID
     *
     * @param pid the value for p_quaninfo.PID
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.EFFDATE
     *
     * @return the value of p_quaninfo.EFFDATE
     *
     * @mbggenerated
     */
    public Date getEffdate() {
        return effdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.EFFDATE
     *
     * @param effdate the value for p_quaninfo.EFFDATE
     *
     * @mbggenerated
     */
    public void setEffdate(Date effdate) {
        this.effdate = effdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.INVALDATE
     *
     * @return the value of p_quaninfo.INVALDATE
     *
     * @mbggenerated
     */
    public Date getInvaldate() {
        return invaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.INVALDATE
     *
     * @param invaldate the value for p_quaninfo.INVALDATE
     *
     * @mbggenerated
     */
    public void setInvaldate(Date invaldate) {
        this.invaldate = invaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_quaninfo.PARAMSTATE
     *
     * @return the value of p_quaninfo.PARAMSTATE
     *
     * @mbggenerated
     */
    public String getParamstate() {
        return paramstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_quaninfo.PARAMSTATE
     *
     * @param paramstate the value for p_quaninfo.PARAMSTATE
     *
     * @mbggenerated
     */
    public void setParamstate(String paramstate) {
        this.paramstate = paramstate == null ? null : paramstate.trim();
    }
}