package com.ebs.model;

import java.util.Date;

public class RoleBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.ROLECODE
     *
     * @mbggenerated
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.SRLNO
     *
     * @mbggenerated
     */
    private Long srlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.PARAMSRLNO
     *
     * @mbggenerated
     */
    private Long paramsrlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.ROLENAME
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.ROLETYPE
     *
     * @mbggenerated
     */
    private String roletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.DEPTYPECODE
     *
     * @mbggenerated
     */
    private String deptypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.FLOWROLECODE
     *
     * @mbggenerated
     */
    private String flowrolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.EFFDATE
     *
     * @mbggenerated
     */
    private Date effdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.INVALDATE
     *
     * @mbggenerated
     */
    private Date invaldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_role.PARAMSTATE
     *
     * @mbggenerated
     */
    private String paramstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.ROLECODE
     *
     * @return the value of p_role.ROLECODE
     *
     * @mbggenerated
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.ROLECODE
     *
     * @param rolecode the value for p_role.ROLECODE
     *
     * @mbggenerated
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.SRLNO
     *
     * @return the value of p_role.SRLNO
     *
     * @mbggenerated
     */
    public Long getSrlno() {
        return srlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.SRLNO
     *
     * @param srlno the value for p_role.SRLNO
     *
     * @mbggenerated
     */
    public void setSrlno(Long srlno) {
        this.srlno = srlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.PARAMSRLNO
     *
     * @return the value of p_role.PARAMSRLNO
     *
     * @mbggenerated
     */
    public Long getParamsrlno() {
        return paramsrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.PARAMSRLNO
     *
     * @param paramsrlno the value for p_role.PARAMSRLNO
     *
     * @mbggenerated
     */
    public void setParamsrlno(Long paramsrlno) {
        this.paramsrlno = paramsrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.ROLENAME
     *
     * @return the value of p_role.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.ROLENAME
     *
     * @param rolename the value for p_role.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.ROLETYPE
     *
     * @return the value of p_role.ROLETYPE
     *
     * @mbggenerated
     */
    public String getRoletype() {
        return roletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.ROLETYPE
     *
     * @param roletype the value for p_role.ROLETYPE
     *
     * @mbggenerated
     */
    public void setRoletype(String roletype) {
        this.roletype = roletype == null ? null : roletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.DEPTYPECODE
     *
     * @return the value of p_role.DEPTYPECODE
     *
     * @mbggenerated
     */
    public String getDeptypecode() {
        return deptypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.DEPTYPECODE
     *
     * @param deptypecode the value for p_role.DEPTYPECODE
     *
     * @mbggenerated
     */
    public void setDeptypecode(String deptypecode) {
        this.deptypecode = deptypecode == null ? null : deptypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.FLOWROLECODE
     *
     * @return the value of p_role.FLOWROLECODE
     *
     * @mbggenerated
     */
    public String getFlowrolecode() {
        return flowrolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.FLOWROLECODE
     *
     * @param flowrolecode the value for p_role.FLOWROLECODE
     *
     * @mbggenerated
     */
    public void setFlowrolecode(String flowrolecode) {
        this.flowrolecode = flowrolecode == null ? null : flowrolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.REMARKS
     *
     * @return the value of p_role.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.REMARKS
     *
     * @param remarks the value for p_role.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.EFFDATE
     *
     * @return the value of p_role.EFFDATE
     *
     * @mbggenerated
     */
    public Date getEffdate() {
        return effdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.EFFDATE
     *
     * @param effdate the value for p_role.EFFDATE
     *
     * @mbggenerated
     */
    public void setEffdate(Date effdate) {
        this.effdate = effdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.INVALDATE
     *
     * @return the value of p_role.INVALDATE
     *
     * @mbggenerated
     */
    public Date getInvaldate() {
        return invaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.INVALDATE
     *
     * @param invaldate the value for p_role.INVALDATE
     *
     * @mbggenerated
     */
    public void setInvaldate(Date invaldate) {
        this.invaldate = invaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_role.PARAMSTATE
     *
     * @return the value of p_role.PARAMSTATE
     *
     * @mbggenerated
     */
    public String getParamstate() {
        return paramstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_role.PARAMSTATE
     *
     * @param paramstate the value for p_role.PARAMSTATE
     *
     * @mbggenerated
     */
    public void setParamstate(String paramstate) {
        this.paramstate = paramstate == null ? null : paramstate.trim();
    }
}