package com.ebs.model;

import java.util.Date;

public class UserBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.USERCODE
     *
     * @mbggenerated
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.SRLNO
     *
     * @mbggenerated
     */
    private Long srlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.PARAMSRLNO
     *
     * @mbggenerated
     */
    private Long paramsrlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.PWD
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.OFDEPART
     *
     * @mbggenerated
     */
    private String ofdepart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.WORKPROP
     *
     * @mbggenerated
     */
    private String workprop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.USERSTATE
     *
     * @mbggenerated
     */
    private String userstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.LOGINMODE
     *
     * @mbggenerated
     */
    private String loginmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.LASTUPPWDTIME
     *
     * @mbggenerated
     */
    private Date lastuppwdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.LASTLOGIN
     *
     * @mbggenerated
     */
    private Date lastlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.ORGCODE
     *
     * @mbggenerated
     */
    private String orgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.CRDNTKIND
     *
     * @mbggenerated
     */
    private String crdntkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.CRDNTNO
     *
     * @mbggenerated
     */
    private String crdntno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.UPBIZORGCODE
     *
     * @mbggenerated
     */
    private String upbizorgcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.USEROPTTYPE
     *
     * @mbggenerated
     */
    private String useropttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.APPLYFLAG
     *
     * @mbggenerated
     */
    private String applyflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.USERTPE
     *
     * @mbggenerated
     */
    private String usertpe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.QUERYDEGREE
     *
     * @mbggenerated
     */
    private Integer querydegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.CHKENDDATE
     *
     * @mbggenerated
     */
    private Date chkenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.PWDERRNUM
     *
     * @mbggenerated
     */
    private Integer pwderrnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.CHECKSTARTDATE
     *
     * @mbggenerated
     */
    private Date checkstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_user.MANAGEFlAG
     *
     * @mbggenerated
     */
    private String manageflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.USERCODE
     *
     * @return the value of p_user.USERCODE
     *
     * @mbggenerated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.USERCODE
     *
     * @param usercode the value for p_user.USERCODE
     *
     * @mbggenerated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.SRLNO
     *
     * @return the value of p_user.SRLNO
     *
     * @mbggenerated
     */
    public Long getSrlno() {
        return srlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.SRLNO
     *
     * @param srlno the value for p_user.SRLNO
     *
     * @mbggenerated
     */
    public void setSrlno(Long srlno) {
        this.srlno = srlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.PARAMSRLNO
     *
     * @return the value of p_user.PARAMSRLNO
     *
     * @mbggenerated
     */
    public Long getParamsrlno() {
        return paramsrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.PARAMSRLNO
     *
     * @param paramsrlno the value for p_user.PARAMSRLNO
     *
     * @mbggenerated
     */
    public void setParamsrlno(Long paramsrlno) {
        this.paramsrlno = paramsrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.USERNAME
     *
     * @return the value of p_user.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.USERNAME
     *
     * @param username the value for p_user.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.PWD
     *
     * @return the value of p_user.PWD
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.PWD
     *
     * @param pwd the value for p_user.PWD
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.OFDEPART
     *
     * @return the value of p_user.OFDEPART
     *
     * @mbggenerated
     */
    public String getOfdepart() {
        return ofdepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.OFDEPART
     *
     * @param ofdepart the value for p_user.OFDEPART
     *
     * @mbggenerated
     */
    public void setOfdepart(String ofdepart) {
        this.ofdepart = ofdepart == null ? null : ofdepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.WORKPROP
     *
     * @return the value of p_user.WORKPROP
     *
     * @mbggenerated
     */
    public String getWorkprop() {
        return workprop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.WORKPROP
     *
     * @param workprop the value for p_user.WORKPROP
     *
     * @mbggenerated
     */
    public void setWorkprop(String workprop) {
        this.workprop = workprop == null ? null : workprop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.USERSTATE
     *
     * @return the value of p_user.USERSTATE
     *
     * @mbggenerated
     */
    public String getUserstate() {
        return userstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.USERSTATE
     *
     * @param userstate the value for p_user.USERSTATE
     *
     * @mbggenerated
     */
    public void setUserstate(String userstate) {
        this.userstate = userstate == null ? null : userstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.LOGINMODE
     *
     * @return the value of p_user.LOGINMODE
     *
     * @mbggenerated
     */
    public String getLoginmode() {
        return loginmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.LOGINMODE
     *
     * @param loginmode the value for p_user.LOGINMODE
     *
     * @mbggenerated
     */
    public void setLoginmode(String loginmode) {
        this.loginmode = loginmode == null ? null : loginmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.LASTUPPWDTIME
     *
     * @return the value of p_user.LASTUPPWDTIME
     *
     * @mbggenerated
     */
    public Date getLastuppwdtime() {
        return lastuppwdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.LASTUPPWDTIME
     *
     * @param lastuppwdtime the value for p_user.LASTUPPWDTIME
     *
     * @mbggenerated
     */
    public void setLastuppwdtime(Date lastuppwdtime) {
        this.lastuppwdtime = lastuppwdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.LASTLOGIN
     *
     * @return the value of p_user.LASTLOGIN
     *
     * @mbggenerated
     */
    public Date getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.LASTLOGIN
     *
     * @param lastlogin the value for p_user.LASTLOGIN
     *
     * @mbggenerated
     */
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.ORGCODE
     *
     * @return the value of p_user.ORGCODE
     *
     * @mbggenerated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.ORGCODE
     *
     * @param orgcode the value for p_user.ORGCODE
     *
     * @mbggenerated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode == null ? null : orgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.CRDNTKIND
     *
     * @return the value of p_user.CRDNTKIND
     *
     * @mbggenerated
     */
    public String getCrdntkind() {
        return crdntkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.CRDNTKIND
     *
     * @param crdntkind the value for p_user.CRDNTKIND
     *
     * @mbggenerated
     */
    public void setCrdntkind(String crdntkind) {
        this.crdntkind = crdntkind == null ? null : crdntkind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.CRDNTNO
     *
     * @return the value of p_user.CRDNTNO
     *
     * @mbggenerated
     */
    public String getCrdntno() {
        return crdntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.CRDNTNO
     *
     * @param crdntno the value for p_user.CRDNTNO
     *
     * @mbggenerated
     */
    public void setCrdntno(String crdntno) {
        this.crdntno = crdntno == null ? null : crdntno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.UPBIZORGCODE
     *
     * @return the value of p_user.UPBIZORGCODE
     *
     * @mbggenerated
     */
    public String getUpbizorgcode() {
        return upbizorgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.UPBIZORGCODE
     *
     * @param upbizorgcode the value for p_user.UPBIZORGCODE
     *
     * @mbggenerated
     */
    public void setUpbizorgcode(String upbizorgcode) {
        this.upbizorgcode = upbizorgcode == null ? null : upbizorgcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.USEROPTTYPE
     *
     * @return the value of p_user.USEROPTTYPE
     *
     * @mbggenerated
     */
    public String getUseropttype() {
        return useropttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.USEROPTTYPE
     *
     * @param useropttype the value for p_user.USEROPTTYPE
     *
     * @mbggenerated
     */
    public void setUseropttype(String useropttype) {
        this.useropttype = useropttype == null ? null : useropttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.APPLYFLAG
     *
     * @return the value of p_user.APPLYFLAG
     *
     * @mbggenerated
     */
    public String getApplyflag() {
        return applyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.APPLYFLAG
     *
     * @param applyflag the value for p_user.APPLYFLAG
     *
     * @mbggenerated
     */
    public void setApplyflag(String applyflag) {
        this.applyflag = applyflag == null ? null : applyflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.USERTPE
     *
     * @return the value of p_user.USERTPE
     *
     * @mbggenerated
     */
    public String getUsertpe() {
        return usertpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.USERTPE
     *
     * @param usertpe the value for p_user.USERTPE
     *
     * @mbggenerated
     */
    public void setUsertpe(String usertpe) {
        this.usertpe = usertpe == null ? null : usertpe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.QUERYDEGREE
     *
     * @return the value of p_user.QUERYDEGREE
     *
     * @mbggenerated
     */
    public Integer getQuerydegree() {
        return querydegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.QUERYDEGREE
     *
     * @param querydegree the value for p_user.QUERYDEGREE
     *
     * @mbggenerated
     */
    public void setQuerydegree(Integer querydegree) {
        this.querydegree = querydegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.CHKENDDATE
     *
     * @return the value of p_user.CHKENDDATE
     *
     * @mbggenerated
     */
    public Date getChkenddate() {
        return chkenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.CHKENDDATE
     *
     * @param chkenddate the value for p_user.CHKENDDATE
     *
     * @mbggenerated
     */
    public void setChkenddate(Date chkenddate) {
        this.chkenddate = chkenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.PWDERRNUM
     *
     * @return the value of p_user.PWDERRNUM
     *
     * @mbggenerated
     */
    public Integer getPwderrnum() {
        return pwderrnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.PWDERRNUM
     *
     * @param pwderrnum the value for p_user.PWDERRNUM
     *
     * @mbggenerated
     */
    public void setPwderrnum(Integer pwderrnum) {
        this.pwderrnum = pwderrnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.CHECKSTARTDATE
     *
     * @return the value of p_user.CHECKSTARTDATE
     *
     * @mbggenerated
     */
    public Date getCheckstartdate() {
        return checkstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.CHECKSTARTDATE
     *
     * @param checkstartdate the value for p_user.CHECKSTARTDATE
     *
     * @mbggenerated
     */
    public void setCheckstartdate(Date checkstartdate) {
        this.checkstartdate = checkstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_user.MANAGEFlAG
     *
     * @return the value of p_user.MANAGEFlAG
     *
     * @mbggenerated
     */
    public String getManageflag() {
        return manageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_user.MANAGEFlAG
     *
     * @param manageflag the value for p_user.MANAGEFlAG
     *
     * @mbggenerated
     */
    public void setManageflag(String manageflag) {
        this.manageflag = manageflag == null ? null : manageflag.trim();
    }
}